In [1]:
import pandas as pd
from scipy.stats import chi2_contingency

In [2]:
data = {
    "region": (
        ["North"] * 25 +
        ["South"] * 25 +
        ["East"] * 25 +
        ["West"] * 25
    ),
    "rating": (
        # North
        ["5-star"] * 10 + ["4-star"] * 8 + ["3-star"] * 5 + ["2-star"] * 2 +
        # South
        ["3-star"] * 8 + ["4-star"] * 7 + ["2-star"] * 6 + ["1-star"] * 4 +
        # East
        ["5-star"] * 12 + ["4-star"] * 8 + ["3-star"] * 5 +
        # West
        ["4-star"] * 10 + ["3-star"] * 8 + ["2-star"] * 5 + ["1-star"] * 2
    )
}

df = pd.DataFrame(data)
df.head()

  region  rating
0  North  5-star
1  North  5-star
2  North  5-star
3  North  5-star
4  North  5-star

In [3]:
df["region"].value_counts(), df["rating"].value_counts()

(region
 North    25
 South    25
 East     25
 West     25
 Name: count, dtype: int64,
 rating
 4-star    33
 3-star    26
 5-star    22
 2-star    13
 1-star     6
 Name: count, dtype: int64)

In [4]:
contingency_table = pd.crosstab(df["region"], df["rating"])
contingency_table

rating  1-star  2-star  3-star  4-star  5-star
region
East         0       0       5       8      12
North        0       2       5       8      10
South        4       6       8       7       0
West         2       5       8      10       0

In [5]:
chi2_stat, p_value, dof, expected = chi2_contingency(contingency_table)

print("Chi-Square Statistic:", chi2_stat)
print("P-value:", p_value)
print("Degrees of Freedom:", dof)

Chi-Square Statistic: 38.65734265734266
P-value: 0.00011982227157217064
Degrees of Freedom: 12

In [6]:
expected_df = pd.DataFrame(
    expected,
    index=contingency_table.index,
    columns=contingency_table.columns
)

expected_df

rating  1-star  2-star  3-star  4-star  5-star
region
East       1.5    3.25     6.5    8.25     5.5
North      1.5    3.25     6.5    8.25     5.5
South      1.5    3.25     6.5    8.25     5.5
West       1.5    3.25     6.5    8.25     5.5

In [7]:
alpha = 0.05

if p_value < alpha:
    print("Reject the Null Hypothesis")
    print("There IS a statistically significant association between customer rating and region.")
else:
    print("Fail to Reject the Null Hypothesis")
    print("There is NO statistically significant association between customer rating and region.")

Reject the Null Hypothesis
There IS a statistically significant association between customer rating and region.